from modules.database import Database
from modules.campaign_engine import CampaignEngine

SIMULATED_DATE = "2026-09-15"
CAMPAIGN_ID = 2
PROSPECT_ID = 5  # zucchi.com / Fausto

print("CUSTOMER COMMITMENT RELEASE TEST")
print(f"Simulated date: {SIMULATED_DATE}")
print()

db = Database()
engine = CampaignEngine(db)

member = db.cursor.execute(
    """
    SELECT
        m.id,
        m.status,
        m.current_step,
        m.next_action_date,
        m.commitment_type,
        m.commitment_date,
        m.commitment_note
    FROM campaign_members m
    WHERE m.campaign_id = ?
      AND m.prospect_id = ?
    LIMIT 1
    """,
    (CAMPAIGN_ID, PROSPECT_ID),
).fetchone()

if not member:
    raise RuntimeError("Campaign member not found.")

print(
    "BEFORE:"
    f" status={member['status']}"
    f" | step={member['current_step']}"
    f" | next={member['next_action_date']}"
    f" | commitment={member['commitment_date']}"
)

# Snapshot event state so the simulation can be completely cleaned up.
last_event = db.cursor.execute(
    "SELECT COALESCE(MAX(id), 0) AS id FROM campaign_events"
).fetchone()
baseline_event_id = last_event["id"]

released = engine.release_due_commitments(SIMULATED_DATE)

print()
print(f"Commitments released: {released}")

after_release = db.cursor.execute(
    """
    SELECT
        id, status, current_step, next_action_date,
        commitment_type, commitment_date
    FROM campaign_members
    WHERE id = ?
    """,
    (member["id"],),
).fetchone()

print(
    "AFTER RELEASE:"
    f" status={after_release['status']}"
    f" | step={after_release['current_step']}"
    f" | next={after_release['next_action_date']}"
)

due = engine.get_due_members(
    campaign_id=CAMPAIGN_ID,
    on_date=SIMULATED_DATE,
)

print()
print("DUE MEMBERS AFTER RELEASE:")
for row in due:
    print(
        f"Member={row['id']} | {row['domain']} | "
        f"Campaign={row['campaign_name']} | "
        f"STEP={row['current_step']} | NEXT={row['next_action_date']}"
    )

print(f"TOTAL DUE: {len(due)}")

# Restore the exact state that existed before the simulation.
db.cursor.execute(
    """
    UPDATE campaign_members
    SET
        status = ?,
        current_step = ?,
        next_action_date = ?,
        commitment_type = ?,
        commitment_date = ?,
        commitment_note = ?
    WHERE id = ?
    """,
    (
        member["status"],
        member["current_step"],
        member["next_action_date"],
        member["commitment_type"],
        member["commitment_date"],
        member["commitment_note"],
        member["id"],
    ),
)

# Remove only events generated by this simulation.
db.cursor.execute(
    """
    DELETE FROM campaign_events
    WHERE id > ?
      AND member_id = ?
      AND event_type = 'CUSTOMER_COMMITMENT_DUE'
    """,
    (baseline_event_id, member["id"]),
)

db.connection.commit()

restored = db.cursor.execute(
    """
    SELECT status, current_step, next_action_date, commitment_date
    FROM campaign_members
    WHERE id = ?
    """,
    (member["id"],),
).fetchone()

print()
print(
    "RESTORED:"
    f" status={restored['status']}"
    f" | step={restored['current_step']}"
    f" | next={restored['next_action_date']}"
    f" | commitment={restored['commitment_date']}"
)

print()
print("No email sent.")
print("Simulation complete.")
